format = """
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$cmd_duration\
$line_break\
$time\
"""

# Usuario
[username]
style_user = "bold #FF2EFF"
style_root = "bold #F9FF00"
format = "[$user]($style) "
show_always = true

# Directorio
[directory]
style = "bold #00FFFF"
format = "[ $path]($style) "
truncation_length = 2
truncation_symbol = "/"

# Git branch
[git_branch]
symbol = " "
style = "bold #FF2EFF"
format = "[$symbol$branch]($style) "

# Git status
[git_status]
style = "bold #F9FF00"
format = "[$all_status$ahead_behind]($style) "

# Node.js
[nodejs]
symbol = " "
style = "bold #00FFFF"
format = "[$symbol($version)]($style) "

# Python
[python]
symbol = " "
style = "bold #F9FF00"
format = "[$symbol$version]($style) "

# Rust
[rust]
symbol = " "
style = "bold #FF2EFF"
format = "[$symbol$version]($style) "

# Duración del comando
[cmd_duration]
style = "bold #E5E5E5"
format = "[⏱ $duration]($style) "

# Opcional: separador de línea
[line_break]
disabled = false

[docker_context]
symbol = " "
style = "bold #00FFFF"

[time]
disabled = false
time_format = "%H:%M"
style = "bold #F9FF00"
format = "[ $time]($style) "
